// React/my_project/src/components/Header/Header.tsx
import "./Header.css";
import logo from "../../assets/logo_black.svg";
import React from "react";

interface HeaderProps {
  showLogoutButton: boolean;
  onLogout?: () => void;
}

const Header: React.FC<HeaderProps> = ({ showLogoutButton, onLogout }) => {
  return (
    <header className="header">
      <img src={logo} alt="Logo" className="logo" />
      <div className="header-right">
        {showLogoutButton && (
          <button className="logout-btn" onClick={onLogout}>
            Logout
          </button>
        )}
      </div>
    </header>
  );
};

export default Header;

// Angular/first-ng-app/src/app/components/header/header.component.ts
import { Component, Input, Output, EventEmitter } from '@angular/core';
import { Router } from '@angular/router';

@Component({
  selector: 'app-header',
  templateUrl: './header.component.html',
  styleUrls: ['./header.component.css'],
})
export class HeaderComponent {
  @Input() showLogoutButton: boolean = false;
  @Output() onLogout = new EventEmitter<void>();

  constructor(private router: Router) {}

  navigateToHome(): void {
    this.router.navigate(['/home']);
  }

  handleKeyDown(event: KeyboardEvent): void {
    if (event.key === 'Enter') {
      this.navigateToHome();
    }
  }

  logout(): void {
    this.onLogout.emit();
  }
}

<header class="header">
  <img
    src="assets/logo_black.svg"
    alt="Logo"
    class="logo"
    (click)="navigateToHome()"
    role="button"
    tabindex="0"
    aria-label="Navigate to home page"
    (keydown)="handleKeyDown($event)"
  />
  <div class="header-right">
    <button
      *ngIf="showLogoutButton"
      class="logout-btn"
      (click)="logout()"
      aria-label="Logout"
    >
      Logout
    </button>
  </div>
</header>
